### ISSUE TITLE
Beta Page is down since July/09/2017

### ISSUE THREAD

**Issue by SophieFields** [doxxx/ffxiv-craft-opt-web#146]
Hi.
I love your page. But since your update for stormblood is the site not available. Please check it out.
Bye

**Comment by SophieFields** [comment]
The page is just white with google chrome. With microsoft edge it just works fine.

**Comment by doxxx** [comment]
Try holding down Ctrl and Shift and clicking the Reload button in Chrome.

**Comment by Battler624** [comment]
working here.

**Comment by danj2k** [comment]
working in Chrome here also.

**Comment by belazor** [comment]
`[Error] Error: null is not an object (evaluating 'response.data.action')
http://ffxiv-beta.lokyst.net/js/services/xivdbtooltips.js:42:39
[native code]
K@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.32/angular.min.js:102:156
https://ajax.googleapis.com/ajax/libs/angularjs/1.2.32/angular.min.js:103:322
$digest@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.32/angular.min.js:111:173
https://ajax.googleapis.com/ajax/libs/angularjs/1.2.32/angular.min.js:114:186
e@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.32/angular.min.js:37:502
https://ajax.googleapis.com/ajax/libs/angularjs/1.2.32/angular.min.js:41:362
	(anonymous function) (angular.min.js:69)
	K (angular.min.js:102:184)
	(anonymous function) (angular.min.js:103:323)
	$digest (angular.min.js:111:174)
	(anonymous function) (angular.min.js:114:187)
	e (angular.min.js:37:503)
	(anonymous function) (angular.min.js:41:363)`

`[Error] Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) (angular-ui-router.js.map, line 0) https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/1.0.0-rc.1/angular-ui-router.js.map`

`XMLHttpRequest cannot load https://secure.xivdb.com/tooltip?language=en&list[action]:=100090,100030,100015,100001,100105,100075,100045,100060,100096,100037,100021,100007,100111,100080,100051,100067,100083,100063,100069,100039,100033,100091,100031,100016,100002,100106,100076,100046,100061,100093,100034,100018,100004,100109,100078,100048,100064,100097,100038,100022,100008,100112,100081,100052,100068,100108,100009,286,276,100092,100032,100017,100003,100107,100077,100047,100062,100094,100035,100019,100005,100110,100079,100049,100065,279,285,278,258,254,253,252,259,255,257,256,250,246,245,244,251,247,249,248,281,277,283,266,262,261,260,267,263,265,264,284,100098,100126,100122,100121,100120,100127,100123,100124,100125,100134,100130,100129,100128,100135,100131,100132,100133,100178,100136,100175,100171,100170,100169,100176,100172,100173,100174,100193,100189,100188,100187,100194,100190,100191,100192,100143,100139,100138,100137,100144,100140,100141,100142,100159,100155,100154,100153,100160,100156,100157,100158,100151,100147,100146,100145,100152,100148,100149,100150,100167,100163,100162,100161,100168,100164,100165,100166,100050,100020,100036,100066,100095,100006,4571,4569,4570,4572,4573,4568,100201,100197,100196,100195,100202,100198,100199,100200,100209,100205,100204,100203,100210,100206,100207,100208,100217,100213,100212,100211,100218,100214,100215,100216,100225,100221,100220,100219,100226,100222,100223,100224,4580,4576,4575,4574,4581,4577,4578,4579,100233,100229,100228,100227,100234,100230,100231,100232,100241,100237,100236,100235,100242,100238,100239,100240,100249,100245,100244,100243,100250,100246,100247,100248,100257,100253,100252,100251,100258,100254,100255,100256,100265,100261,100260,100211,100259,100262,100263,100264,100273,100269,100268,100267,100274,100270,100271,100272,100281,100277,100276,100275,100282,100278,100279,100280,50356,50352,50351,50350,50357,50353,50354,50355,100099,100040,100023,100010,100113,100082,100053,100070 due to access control checks.`

**Comment by doxxx** [comment]
That looks like it's failing to load tooltips from XIVDB. I'll have a look.

**Comment by Fenrirthviti** [comment]
Probably unrelated, but the entire page is down as of 07/16/2017:

![down](https://pub.rachni.com/img/chrome_2017-07-17_19-51-12.png)

**Comment by doxxx** [comment]
@Fenrirthviti We recently changed webhosts so you may still be getting the old DNS. You could try running `ipconfig /flushdns` from a command window if you're on Windows, but I'm not really sure if that will help. I had to restart my own router to get it to pick up the new DNS after we moved the site.

**Comment by Cleanse** [comment]
I think the tooltip issue is because you're not running the beta page http://ffxiv-beta.lokyst.net/#/simulator on https. You either need to load the http tooltip lib, or setup a free https://letsencrypt.org/ https on your server.

**Comment by doxxx** [comment]
The issue is intermittent. If it was because of http vs https it would occur more consistently. 

My suspicion is that there's a bug or some other unexplained behavior in the XIVDB API server which causes it to return a 404 Not Found response sometimes when the app requests all the tooltips. 

Have you seen this issue recently?

**Comment by Cleanse** [comment]
I had a similar issue, my server was https and the default example was http, plus he had to tweak a few things related to reading his own api. 

> Embed the script: http://xivdb.com/tooltips.js anywhere in your code. eg:
```
<html>
    <head>
        ...
    </head>
    <body>
        ...
        <script src="https://secure.xivdb.com/tooltips.js"></script>
    </body>
</html>
```

Note his initial quote is not from secure, try using that url.

**Comment by doxxx** [comment]
Ah, I see. I'm not using http://xivdb.com/tooltips.js -- I wrote my own Javascript (as an AngularJS service) which fetches the tooltip data from the XIVDB API using the same method that http://xivdb.com/tooltips.js does.

This was mainly because the majority of what http://xivdb.com/tooltips.js does is implement the necessary DOM hijinks to create the effect of tooltips -- I have AngularJS and Angular-Bootstrap-UI to do that. :)

My service could probably be a bit smarter about fetching tooltip contents on-demand though. Right now it fetches everything in one request, which takes a noticeable amount of time, and may be too much data to ask for in one request.

**Comment by doxxx** [comment]
I've reworked the way tooltips are loaded from XIVDB, so hopefully this problem should be resolved.
