### ISSUE TITLE
I can't save the solver options anymore.

### ISSUE THREAD

**Issue by roswell67** [doxxx/ffxiv-craft-opt-web#166]
Not sure which information you need for this to replicate. My setup is attached.

The save Button is disabled
[settings (4).zip](https://github.com/doxxx/ffxiv-craft-opt-web/files/1176470/settings.4.zip)

**Comment by doxxx** [comment]
Something else to check is to press f12 to open the browser developer tools window and check if there are any errors in the console tab.

**Comment by roswell67** [comment]
No errors, in the developer tools console tab while opening the tab, trying to save. the button is just simply unclickable and looks faded.


![image](https://user-images.githubusercontent.com/10183897/28623292-2d95bac2-721e-11e7-9150-b4d53242121c.png)

Also, I've sent you an email on gordon@doxxx.. Let me know.

**Comment by AndreaSnep** [comment]
I can second the issue, both using imported settings from [0bc4ee6](https://github.com/doxxx/ffxiv-craft-opt-web/commit/0bc4ee6ca9fd35cb870595440c174f304677e2e4) as well as using clean settings.  It seems to be disabled because the Max Length setting has a default value of 0 - setting a non-zero value allows the Save button to function normally from then on.  The breaking change seems to be in [461b228](https://github.com/doxxx/ffxiv-craft-opt-web/commit/461b22833d8def51baf422d6ec4ab500216b53d0): [in app/js/controllers/main.js maxLength is initialized to 0](https://github.com/doxxx/ffxiv-craft-opt-web/commit/461b22833d8def51baf422d6ec4ab500216b53d0#diff-67d03633c2ddd4ab1476f82322f28059R390), but [in app/modals/options.html it has a minimum value of 1](https://github.com/doxxx/ffxiv-craft-opt-web/commit/461b22833d8def51baf422d6ec4ab500216b53d0#diff-a0e97742307bd5d6f316f5614b42165bR85).  

Simply changing the default value of maxLength to a positive number fixes it for new instances (eg. using defaults), but with pre-existing settings users still have to set the value manually.

**Comment by doxxx** [comment]
Ah, damn, and there I thought I got the defaults right for existing users. Sorry about that, I'll fix it later today.

**Comment by doxxx** [comment]
Deployed to beta site. It should automatically fix the saved settings when you reload.
