### ISSUE TITLE
Stats not calculating correctly at level 80

### ISSUE THREAD

**Issue by alostrael444** [doxxx/ffxiv-craft-opt-web#309]
## Required Information

Class: Weaver (specialist)
Level: 80
Craftsmanship: 1833
Control: 1736
CP: 420
Recipe Name: Dwarven Cotton Thread
Recipe Level: 78
Solver Seed: 103748

## Expected Behaviour
100% efficiency is 490 progress as it is in the in-game crafting window

## Actual Behaviour
100% efficiency is 361 progress

## Steps To Reproduce
No special settings.
If I set the level back to 79 and increase my craftsmanship stat until the Simulator display reflects the correct 100% progress number, it works fine. It's worked up until level 80.

**Comment by dax-dev** [comment]
These aren't calculating correctly on my non-80 classes, either. The difference seems to get bigger the higher level my class is. Here are two examples I ran into today:

WVR 38
Craftsmanship 172
Control 179
Cotton Yarn (lvl12)
Progress: 57, in-game: 57
Efficiency: 98, in-game: 99

ARM 78
Craftsmanship 1645
Control 1529
Deepgold Nugget (lvl71)
Progress: 523, in-game: 536
Efficiency: 574, in-game: 585

It's not very consistent across different recipe tiers. Sometimes it's off by 1, sometimes it's off by 20. If the progress is off, then it leads to failed recipes due to them being completed too early.

**Comment by dax-dev** [comment]
Dropping in again, becuase I saw in another thread that the owner is mostly doing bugfixes now, and would need some help if formulas need adjusting.

I'm not a webdev, I mostly work in C. That said, I'm more than willing to help out if I can. If you can point me to where to find the formula in the code and give some pointers on how to tweak it, I'll help get it adjusted. I don't have any knowledge of how the formula currently works or what to tweak, so any guidance here would be appreciated.

**Comment by doxxx** [comment]
Thanks to @yls888 and @SaltFish-X, we have a new set of formulas for progress and quality increase. These changes are available on the beta site (ffxiv-beta.lokyst.net). Please let me know if these discrepancies are resolved.

**Comment by alostrael444** [comment]
Has worked perfectly lately, thank you for the fix!
