### ISSUE TITLE
ffxiv-craf-opt docker container

### ISSUE THREAD

**Issue by Ley21** [doxxx/ffxiv-craft-opt-web#98]
From time to time I have some time to help you to add some informations or add features, which you could merge.
Because of portablility i use docker container. It is possible that you create a docker container from your repository, so I can run it anywhere?

**Comment by doxxx** [comment]
I've found that running a dev web server directly is the easiest way to do
development because it requires such frequent reloading (although I suppose
using a volume for the app files in the container would avoid having to
rebuild all the time...).

However, I can see how a Docker container would be useful and it should be
simple enough to setup. I'll give it a shot myself but let me know if
there's any specific Docker features you would like or if you have a
Dockerfile that you would like to share.

**Comment by doxxx** [comment]
You may want to `npm dedupe` and `npm prune` to reduce how much build context is sent to Docker.
